oi

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,9 +11,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-     - name: Succesful step
+     - name: Failedl step
        run: |
-        echo "I will not fail"
-        exit 0
+        echo "I will fail"
+        exit 1
      - name: Say Goodbye
        run: echo "Goodbye!"
